# These settings are used by the Python functions open_sdg_build() and
# open_sdg_check(), from sdg-build.

# List of languages for translated builds.
languages:
  - en

# Where the data gets built.
site_dir: _site

# The file to use for the metadata schema.
schema_file: _prose.yml

# The parent folder of the 'meta' and 'data' folders.
src_dir: ''

# Links to Git repositories with translation data.
translations:
  - https://github.com/open-sdg/translations-un-sdg.git@1.0.0-rc1
  - https://github.com/open-sdg/translations-open-sdg.git@1.0.0-rc5

# Extra fields to generate reporting stats for, for additional tabs
# the "Reporting status" page.
reporting_status_extra_fields: []

# This builds one or more GeoJSON files to be used by Open SDG maps. For more
# information on the parameters, see the sdg-build library.
map_layers: []
# To use this, remove the "[]" in the line above and uncomment/configure below:
#  - geojson_file: regions.geojson
#    name_property: myNameProperty
#    id_property: myIdProperty
#    output_subfolder: regions
#    filename_prefix: indicator_
